Proposal for new bvh split method (approach Nr. 3) - divide and conquer with std::sort()
RayTracing/raytracing.github.io pull request #1391
Opened 2024-02-19 00:05 UTC by relief7

Hi Steve!

please find proposal for "new bvh split method (approach Nr. 3) - divide and conquer with std::sort()" based on latest dev branch in this pull request (see further info in issue reply).

Thanks,
Markus

2024-02-20 09:02 UTC, hollasch requested changes
If you agree to these changes, then we also need to do the following work:
- Make the same changes to bvh.h in `src/TheRestOfYourLife`.
- Update the text and any listings for books 2 & 3
- Add an entry to the CHANGELOG.md file.
- Please add your name to `books/acknowledgments.md`.

2024-02-20 09:02 UTC, hollasch commented on src/TheNextWeek/bvh.h
>              bbox = aabb(bbox, src_objects[object_index]->bounding_box());
Simplify to:

    for (auto& obj : src_objects)
        bbox = aabb(bbox, obj->bounding_box());

2024-02-20 09:02 UTC, hollasch commented on src/TheNextWeek/bvh.h
> +        size_t size = src_objects.size ();
Move `size` definition down below the line:

    auto objects = src_objects; // A modifiable array of the source scene objects

2024-02-20 09:02 UTC, hollasch commented on src/TheNextWeek/bvh.h
>              }
Since we're rewriting this, let's fix issue #1327 in the same commit. Please simplify this case to the following:

    ...
    } else if (size == 2) {
        left = objects[0];
        right = objects[1];
    } else {
    ...

(Ordering the two child objects in this case accomplishes nothing.)

2024-02-20 15:53 UTC, relief7 commented
Hi Steve!
Thank you for the great feedback! I totally forgot about the code in the other chapters and the book! 🤣 
Will try to do another round and re-submit! After all these changes, the bvh construction will be so easy that even a pre-schooler can understand it. 😄  
Thanks,
Markus

2024-02-23 10:33 UTC, wlbksy commented
You can improve further by writing a helper function to do the job.
1. `bvh_node(const vector& objs)` first sort all the objects.
2. call the helper function to do the split job so that you don't have to sort every level down the tree.

2024-02-23 18:04 UTC, relief7 commented
Hi @wlbksy!
Thank you for your suggestion! I am not sure if I can follow though... Don't we need to sort in every level because we are randomly switching up the axis of sorting in each level?

```
int axis = random_int(0,2);
auto comparator = (axis == 0) ? box_x_compare
                : (axis == 1) ? box_y_compare
                              : box_z_compare;
```

So a good sort for x in the beginning might not be an optimal sort for z a few levels further down, for example. Or am I misunderstanding this issue?

2024-02-23 19:08 UTC, armansito commented
> Hi @wlbksy! Thank you for your suggestion! I am not sure if I can follow though... Don't we need to sort in every level because we are randomly switching up the axis of sorting in each level?
> 
> ```
> int axis = random_int(0,2);
> auto comparator = (axis == 0) ? box_x_compare
>                 : (axis == 1) ? box_y_compare
>                               : box_z_compare;
> ```
> 
> So a good sort for x in the beginning might not be an optimal sort for z a few levels further down, for example. Or am I misunderstanding this issue?

I agree, you need to know the spatial subdivision axis and position at each level  and the BVH construction code is already handling this.

As an alternative, if we really wanted to eliminate all the redundant copies and vector allocations, we could allow the BVH construction to sort the object list in-place without creating any intermediate vectors. The code would look very similar to the original listing but instead remove the `const` qualifier from the `src_objects` declaration. If preserving the original order of the input objects is important, the input could be copied _once_ and the in-place sort could operate over that initial copy (but I'm not sure if that's is really necessary).

@hollasch any thoughts?

2024-02-23 20:09 UTC, relief7 commented
Hi @armansito 

I personally think that this is a great idea! It would probably be super fast and efficient. 

I always wondered why we are doing the indexing *and* copying the vector in the first place because doing both kind of negate each other.

My proposal works around the issue to simplify the indexing (because it would not be needed) but what you are suggesting is probably the most elegant solution with the smallest RAM and CPU footprint. 😄

2024-02-24 16:32 UTC, wlbksy commented
> Hi @wlbksy! Thank you for your suggestion! I am not sure if I can follow though... Don't we need to sort in every level because we are randomly switching up the axis of sorting in each level?
> 
> ```
> int axis = random_int(0,2);
> auto comparator = (axis == 0) ? box_x_compare
>                 : (axis == 1) ? box_y_compare
>                               : box_z_compare;
> ```
> 
> So a good sort for x in the beginning might not be an optimal sort for z a few levels further down, for example. Or am I misunderstanding this issue?

Oh, you're right. I missed this random axis switching.

2024-02-26 15:18 UTC, closed without merging

2024-02-26 18:11 UTC, relief7 commented
Hi! 
apologies for closing and opening a new pull request (still trying to get the hang of github 😆).

I made some tests with your suggestions, @armansito (see results in my previous bvh thread #1388 ).

IMHO, this would be the most elegant solution to most issues, so a new bvh method such as the one from my original proposal would not really be needed anymore. There is also a pull request #1409 with corresponding code and book changes, Steve @hollasch , in case you find it useful.

Thanks!

2024-02-26 23:24 UTC, hollasch commented
> @[relief7](https://github.com/relief7) relief7 [force-pushed](https://github.com/RayTracing/raytracing.github.io/compare/7e62d8e94d20007a2c1b37c5dc43149da9db9d8f..b11548c7783a6dd1a3dfdb50192b4a3959608f77) the dev branch from [7e62d8e ](https://github.com/RayTracing/raytracing.github.io/commit/7e62d8e94d20007a2c1b37c5dc43149da9db9d8f)to [b11548c ](https://github.com/RayTracing/raytracing.github.io/commit/b11548c7783a6dd1a3dfdb50192b4a3959608f77)
[7 hours ago](https://github.com/RayTracing/raytracing.github.io/pull/1391#event-11923065891)

You didn't force-push the `RayTracing:dev` branch did you?

2024-02-27 17:24 UTC, relief7 commented
> > @[relief7](https://github.com/relief7) relief7 [force-pushed](https://github.com/RayTracing/raytracing.github.io/compare/7e62d8e94d20007a2c1b37c5dc43149da9db9d8f..b11548c7783a6dd1a3dfdb50192b4a3959608f77) the dev branch from [7e62d8e ](https://github.com/RayTracing/raytracing.github.io/commit/7e62d8e94d20007a2c1b37c5dc43149da9db9d8f)to [b11548c ](https://github.com/RayTracing/raytracing.github.io/commit/b11548c7783a6dd1a3dfdb50192b4a3959608f77)
> > [7 hours ago](https://github.com/RayTracing/raytracing.github.io/pull/1391#event-11923065891)
> 
> You didn't force-push the `RayTracing:dev` branch did you?

No, as you can see in the status message:

![image](https://github.com/RayTracing/raytracing.github.io/assets/159066453/7f8746aa-7321-44d7-a4e4-e11d2f475c45)

I am only modifying the ```dev``` branch in my own fork and submitting pr's from there. I wouldn't even have the administrative rights to commit any changes to your repository, would I?

2024-02-27 20:32 UTC, hollasch commented
_Phew!_ Thanks @relief7.