correct call to reflectance()
RayTracing/raytracing.github.io pull request #1418
Opened 2024-03-06 14:58 UTC by TheThief

reflectance() takes `double ref_idx` (which is `ir` in the outer scope), not `refraction_ratio`. Confirmed with the formula for Schlick's approximation (https://en.wikipedia.org/wiki/Schlick%27s_approximation) which uses two indexes of refraction, of which one is hard coded to `1` in the function here.

A future todo would be to keep track of the "ir of the current medium" in the ray and use that instead of a hard coded `1` in the reflectance formula.

2024-03-06 14:59 UTC, TheThief commented
I previously mentioned this here: https://github.com/RayTracing/raytracing.github.io/issues/1278#issuecomment-1788597280 but it took me a little while to get around to making the pull request

2024-03-06 15:18 UTC, TheThief commented
Note: you'd think this would end up calculating reflectance wrong when leaving the sphere or with the inverted sphere, thinking that maybe it should be `ref_idx-1` instead of `1-ref_idx` (with the two ir's the other way round in the Schlick formula) but as it immediately squares it these actually end up equivalent and it doesn't matter.

2024-03-06 21:49 UTC, hollasch requested changes
This change lacks an update to book 3.

2024-03-06 21:50 UTC, hollasch commented
If you would like, add an entry for yourself in books/acknowledgments.md.html.

2024-03-11 01:21 UTC, hollasch commented
I've gone ahead and made the changes. See PR #1426.

2024-03-11 01:22 UTC, hollasch commented
@TheThief — let me know if you'd like an entry in the acknowledgments.

2024-03-11 01:22 UTC, closed without merging

2024-03-11 08:55 UTC, TheThief commented
> @TheThief — let me know if you'd like an entry in the acknowledgments.

@hollasch If you would be so kind, you could credit me in the Acknowledgements as "Gareth Martin"

I'm sorry I didn't get the changes made myself, I've been busy

2024-03-11 09:01 UTC, TheThief commented
I see your link to #1420 and I think this fix breaks that idea - the Schlick formula specifically needs to know the two IRs, not the ratio, so representing the inner bubble of air as 1/ir isn't helpful in general as we need 1 and the ir for the Schlick formula. It's possible to detect an ir<1.0 and invert it - but that only works in specifically the case of air inside another medium, not e.g. _water_ inside the glass sphere.