Book 1 progression updates
RayTracing/raytracing.github.io pull request #1465
Opened 2024-03-27 21:27 UTC by rupsis

2024-03-27 21:58 UTC, hollasch requested changes

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +Complete building and running instructions can be found on the [project's Github][compiling]
Lacks a period.

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +Complete building and running instructions can be found on the [project's Github][compiling]
"on the project's Github" → "in the project README."

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +        cam.defocus_angle = 10.0;
We generally (but not always) omit decimal points for integer values, and where C++ type resolution can implicitly handle the conversion at compile time.

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +        cam.defocus_angle = 10.0;
For example, `color(0,0,0)`, `color(1,1,1)`, and so forth.

One exception would be when using the `auto` keyword, where the scalar type is required.

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +your scenes.
Please keep Markdeep lines to 100 characters where possible.

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +[compiling]:          https://github.com/RayTracing/raytracing.github.io?tab=readme-ov-file#building-and-running
When referring to the project readme, prefer the local copy, as people can download and use the material offline, and the current version may lack information or have different information that once applied to an older version.

```
[readme]: ./README.md
```

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +Complete building and running instructions can be found on the [project's Github][compiling].
As before.

2024-03-27 21:58 UTC, hollasch commented on src/InOneWeekend/hittable_list.h
> +using std::make_shared;
Odd; these should not be necessary — they're part of `rtweekend.h`. If they're not present at this point, they should be added to `rtweekend.h`.

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +    ...
We generally understand an implicit leading `...` and trailing `...` for listings when changes are scoped to an existing function or class.

2024-03-27 21:58 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +Note the third option, we could scatter with some fixed probability $p$ and have attenuation be
To accomplish this with punctuation, I think that `,` should be `:`.

2024-03-27 21:58 UTC, hollasch commented on images/img-1.16-glass-always-refract.png
This looks wrong.

2024-03-27 21:58 UTC, hollasch commented on images/img-1.16-glass-always-refract.png
The first image should look identical to the second, except where reflection is happening near the edges.

2024-03-27 21:58 UTC, hollasch commented on images/img-1.18-glass-hollow.png
Did we neglect to set the sphere material back to glass here?

2024-03-28 13:59 UTC, rupsis commented on images/img-1.16-glass-always-refract.png
Yeah sorry, I meant to write up a description of this when I made the draft PR, I just ran out of time. 
I added this images because:
1) they are what I've obtained through the progression. 
2) they are wrong. 

Do we want to keep the blue color for the middle sphere, and the shiny metal for the left one? 
Obviously the glass refractions are wrong, I need to investigate the issue.

2024-03-28 14:01 UTC, rupsis commented on images/img-1.18-glass-hollow.png
That's my suspicion. Will investigate.

2024-03-28 16:33 UTC, rupsis commented on images/img-1.23-book1-final.jpg
Changes can be best seen using Githubs "Onion Skin" viewer on the diff. 

Mostly just changes to the location of the spheres. Not sure if it's worth updating or not.

2024-03-28 17:14 UTC, hollasch commented on images/img-1.16-glass-always-refract.png
I'm so confused. Sadly, this is par for the course when doing a progression — it always amazes me how much cruft this chases out. I'll look into this today to see if I can figure anything out. I don't recall any decision to change the color of the middle sphere, and the right sphere going from shiny to fuzzy worries me that I fumbled something during the constructor updates. _Sigh_.

2024-03-28 17:16 UTC, hollasch commented on images/img-1.23-book1-final.jpg
I'm updating a lot of images with minor changes, just to keep things consistent.

2024-03-28 20:18 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +        cam.defocus_angle = 10.0;
Hah! Later on:
```
        cam.focus_dist    = 10.0;
```

Oy vey. I'm so bad.

2024-03-28 20:21 UTC, hollasch commented on books/RayTracingInOneWeekend.html
> +        cam.defocus_angle = 10.0;
Now I'm for keeping your change.

2024-03-28 20:27 UTC, hollasch commented on src/InOneWeekend/hittable_list.h
> +using std::make_shared;
Oh yuck. `rtweekend.h` doesn't exist yet. Also, after introducing `rtweekend.h`, I don't think we include changes to all other header files to remove now-unneeded declarations and definitions.

→ #1473

2024-03-29 02:55 UTC, closed without merging