Book 3 review, Chapters 1-3
RayTracing/raytracing.github.io pull request #972
Opened 2021-12-18 22:17 UTC by trevordblack

Consolidated and simplified so that the rest of the book can be much easier to edit

Replaces #968

2021-12-23 18:32 UTC, hollasch requested changes

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +For the intervals that we don't explicitly set a probability, we assume the PDF to be zero. So for
“For the intervals without an explicit probability, …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
No blank line after H2 lines.

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +uniformly sampled between 0 and 2. We didn't know it at the time, but we were implicitly using a
“… we used a Monte Carlo approach, uniformly sampling from the interval $[0,2]$.”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +within this distribution. We are no longer multiplying the output sum by $2$ to arrive at the final answer. We were previously multiplying the average over the interval (sum/N) times the length of th
Needs to be line wrapped.

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +within this distribution. We are no longer multiplying the output sum by $2$ to arrive at the final answer. We were previously multiplying the average over the interval (sum/N) times the length of th
“… within this distribution. ~We are no longer multiplying the output sum by $2$ to arrive at the final answer.~ We were previously multiplying the average over the interval (sum/N) times the length of the interval ($b - a = 2$). Here, we don't need to multiply by the interval length--that is, we no longer need to multiply the output sum by $2$ to arrive at the final answer.”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +nonuniformity will introduce bias in our scene, indeed this bias is the source of our inaccurately
“… will introduce bias in our scene. Indeed, this bias …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +bright image, so if we account for nonuniformity, we will get accurate results. The PDF will "steer"
“… bright image--if we account …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +will introduce bias. To remove bias we need to down-weight where we sample more frequently, and
“… converge faster, but at the cost of introducing bias. To remove this bias, we need …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +to up-weight where we sample less frequently. For our new nonuniform random number generator the PDF
“… random number generator, the PDF …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +proportional to $1/\text{pdf}$. In fact it is exactly $1/\text{pdf}$. This is why we divide `x*x` by
“In fact, it is _exactly_ $1/\text{pdf}$.”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +solve for both the CDF for, and the inverse of the CDF. If we do that, all we need to do is rewrite
“… linear PDF $p(r) = \frac{r}{2}$, for which we were able to solve both the CDF and its inverse.”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +If you compared the runs from the uniform PDF and the linear PDF you would have probably found that
“… the linear PDF, you would have …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +the linear PDF was converging faster. If you think about it, a linear PDF is probably a better
“… linear PDF converged faster.”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +faster. But, if that's the case, then we should just try to make the PDF match the integrand by
“~But, if~ If that's the case, …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +For just 1 sample we get:
“For just one sample we get:”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +In all of the examples given we always converged to the correct answer of $8/3$. We got the same
“… the examples given, we always …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +they both converged to the same answer, the uniform PDF took much longer, after all, we only needed
“… took much longer. After all, we only …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +Indeed, this is the case for any PDF that you create. They
Wrap paragraph.

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +Indeed, this is the case for any PDF that you create. They
“… that you create--they will all …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +Even the naive PDF above that split the distribution into two halves: 0 to $\sqrt{2}$ and $\sqrt{2}$
“above that”? Seems like this could be deleted, but I'm not clear what you're trying to convey here.

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +to 2. That will converge. Indeed it will converge more quickly than a pure uniform
“… into two halves: $[0,\sqrt{2}]$ and $(\sqrt{2},2]$.”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
> +to 2. That will converge. Indeed it will converge more quickly than a pure uniform
“Indeed, it will converge …”

2021-12-23 18:32 UTC, hollasch commented on books/RayTracingTheRestOfYourLife.html
>  Those were most of the concepts that underlie Monte Carlo ray tracers. Let's review:
“Let's review the main concepts that underlie Monte Carlo ray tracers:”

2021-12-24 21:50 UTC, trevordblack commented
@dafhi Can you poke through? I believe I addressed your earlier concerns

2021-12-27 22:01 UTC, trevordblack commented
@hollasch

2022-01-02 07:06 UTC, hollasch approved these changes

2022-01-02 07:07 UTC, hollasch approved these changes

2022-01-02 07:07 UTC, merged